on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
      - develop

env:
  POETRY_VERSION: 1.1.13
  PY37: 3.7.13
  PY38: 3.8.12
  PY39: 3.9.13

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['${{ env.PY37 }}', '${{ env.py38 }}', '${{ env.PY39 }}']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Poetry cache
        id: cache-poetry-cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pypoetry
          # Look to see if there is a cache hit for the corresponding
          key: poetry-cache-${{ matrix.python-version }}-${{ runner.os }}-${{ env.POETRY_VERSION }}
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ matrix.python-version }}-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Flake8
        run: poetry run flake8
      - name: Mypy
        run: poetry run mypy src
      # - name: Pytest
      #   run: poetry run pytest
      - name: Build
        run: poetry build
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: lint_and_build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY39 }}
      - name: Cache Poetry cache
        id: cache-poetry-cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pypoetry
          # Look to see if there is a cache hit for the corresponding
          key: poetry-cache-${{ env.PY39 }}-${{ runner.os }}-${{ env.POETRY_VERSION }}
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.PY39 }}-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Deploy
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
  deploy_develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    needs: lint_and_build
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY39 }}
      - name: Cache Poetry cache
        id: cache-poetry-cache
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pypoetry
          # Look to see if there is a cache hit for the corresponding
          key: poetry-cache-${{ env.PY39 }}-${{ runner.os }}-${{ env.POETRY_VERSION }}
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ env.PY39 }}-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Deploy
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
